FROM python:3.8

WORKDIR /workdir

RUN apt-get update && apt-get install -y gettext

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

RUN groupadd -r data_registry && useradd --no-log-init -r -g data_registry data_registry

# for exporter
RUN mkdir -p /data/storage
RUN chown -R data_registry /data/storage

USER data_registry:data_registry

COPY --chown=data_registry:data_registry . .

RUN python manage.py compilemessages

RUN VERSION=$(date +%Y%m%d%h%s); sed -i "s/STATIC_VERSION \?=.*/STATIC_VERSION = '$VERSION'/g" ./core/settings/docker.py
