FROM nikolaik/python-nodejs:python3.8-nodejs18 as build-stage

COPY requirements.txt /tmp/requirements.txt
RUN pip install --no-cache-dir -r /tmp/requirements.txt

WORKDIR /workdir

COPY package*.json ./
RUN npm install

COPY . .

ENV DJANGO_ENV=production

RUN npx webpack --mode production
RUN python manage.py collectstatic --noinput -v2

FROM nginxinc/nginx-unprivileged:latest as production-stage
USER root
COPY --from=build-stage --chown=nginx:root /workdir/static /usr/share/nginx/html/static
USER nginx
