version: "2.2"
services:
  django:
    image: "170654793963.dkr.ecr.eu-central-1.amazonaws.com/data-registry:production"
    command: "./gunicorn_runner.sh"
    network_mode: "host"
    restart: unless-stopped
    volumes:
      - /data:/data
  exporter:
    image: "170654793963.dkr.ecr.eu-central-1.amazonaws.com/data-registry:production"
    command: "python manage.py exporter --settings=core.settings.amy01"
    network_mode: "host"
    restart: unless-stopped
    volumes:
      - /data:/data
    scale: 2
  cbom:
    image: "170654793963.dkr.ecr.eu-central-1.amazonaws.com/data-registry:production"
    command: "python manage.py cbom --settings=core.settings.amy01"
    network_mode: "host"
    volumes: