FROM nikolaik/python-nodejs:python3.8-nodejs16 as build-stage

WORKDIR /workdir

COPY package*.json ./
RUN npm install

COPY requirements.txt /tmp/requirements.txt
RUN pip install --no-cache-dir -r /tmp/requirements.txt

COPY . .

ENV DJANGO_ENV=production

RUN npx webpack --mode production
RUN python manage.py collectstatic --noinput

FROM nginxinc/nginx-unprivileged:latest as production-stage
USER root
COPY --from=build-stage --chown=nginx:root /workdir/static /usr/share/nginx/html/static
USER nginx
