version: "2.2"
services:
  django:
    image: "ghcr.io/open-contracting/data-registry-django:latest"
    command: "./gunicorn_runner.sh 8002"
    network_mode: "host"
    env_file:
      - data-registry.env
    restart: unless-stopped
    volumes:
      - /data:/data
  exporter:
    image: "ghcr.io/open-contracting/data-registry-django:latest"
    command: "python manage.py exporter --settings=core.settings.docker"
    network_mode: "host"
    env_file:
      - data-registry.env
    restart: unless-stopped
    volumes:
      - /data:/data
    scale: 2
  wiper:
      image: "ghcr.io/open-contracting/data-registry-django:latest"
      command: "python manage.py wiper --settings=core.settings.docker"
      network_mode: "host"
      env_file:
        - data-registry.env
      restart: unless-stopped
      volumes:
        - /data:/data
      scale: 1
  cbom:
    image: "ghcr.io/open-contracting/data-registry-django:latest"
    command: "python manage.py cbom --settings=core.settings.docker"
    network_mode: "host"
    env_file:
      - data-registry.env
    volumes:
      - /data:/data
  static:
    image: "ghcr.io/open-contracting/data-registry-static:latest"
    ports:
      - "8003:80"
    env_file:
      - data-registry.env
    volumes:
      - /data:/data