# Generated by Django 3.1.6 on 2021-04-01 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_registry', '0003_auto_20210329_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='summary',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue', to='data_registry.collection')),
            ],
        ),
    ]
