# Generated by Django 3.2 on 2021-05-07 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data_registry", "0010_collection_spider"),
    ]

    operations = [
        migrations.RenameField(
            model_name="collection",
            old_name="spider",
            new_name="source_id",
        ),
    ]
