# Generated by Django 3.2 on 2021-05-10 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_registry", "0011_rename_spider_collection_source_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="context",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
