# Generated by Django 3.2 on 2021-05-11 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_registry", "0013_auto_20210511_0846"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="language",
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name="collection",
            name="ocds_label",
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name="collection",
            name="source_id",
            field=models.CharField(max_length=2048),
        ),
        migrations.AlterField(
            model_name="collection",
            name="summary",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="note",
            field=models.TextField(blank=True, null=True),
        ),
    ]
