# Generated by Django 3.2 on 2021-05-13 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("data_registry", "0017_auto_20210512_1230"),
    ]

    operations = [
        migrations.CreateModel(
            name="License",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(blank=True, max_length=2048, null=True)),
                ("description", models.TextField()),
                ("url", models.CharField(blank=True, max_length=2048, null=True)),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ("modified", models.DateTimeField(auto_now=True, db_index=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="collection",
            name="license_custom",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="collection",
                to="data_registry.license",
            ),
        ),
    ]
