# Generated by Django 3.2 on 2021-05-25 10:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_registry", "0019_auto_20210513_0527"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="awards_items_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="collection",
            name="awards_suppliers_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="collection",
            name="contracts_items_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="collection",
            name="contracts_transactions_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="collection",
            name="tenderers_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="collection",
            name="tenders_items_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="collection",
            name="additional_data",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="collection",
            name="additional_data_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="collection",
            name="additional_data_es",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="collection",
            name="description_long",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="collection",
            name="description_long_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="collection",
            name="description_long_es",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="collection",
            name="summary",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="collection",
            name="summary_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="collection",
            name="summary_es",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="issue",
            name="description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="issue",
            name="description_en",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="issue",
            name="description_es",
            field=models.TextField(null=True),
        ),
    ]
