# Generated by Django 3.2 on 2021-05-25 10:55
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_registry", "0020_auto_20210525_1055"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="country",
            field=models.CharField(blank=False, max_length=2048, null=False, default="XX"),
            preserve_default=False,
        )
    ]
