# Generated by Django 3.2 on 2021-06-18 12:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("data_registry", "0025_auto_20210618_1208"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="collection",
            name="ocds_label",
        ),
    ]
