# Generated by Django 3.2 on 2021-08-04 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_registry', '0028_auto_20210804_0941'),
        ('data_registry', '0028_auto_20210804_0951'),
    ]

    operations = [
    ]
