# Generated by Django 3.2.4 on 2021-08-27 01:53

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('data_registry', '0030_alter_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='source_url',
            field=models.CharField(blank=True, help_text='The URL of the source OCDS data.', max_length=2048, null=True, verbose_name='Source URL'),
        ),
    ]
