# Generated by Django 3.2.4 on 2021-09-14 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_registry', '0033_collection_source_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='last_reviewed',
            field=models.DateField(blank=True, help_text='The date on which the most recent data feedback report was made. Only the yearand month are important.', null=True, verbose_name='last reviewed'),
        ),
    ]
