# Generated by Django 4.2.3 on 2023-08-17 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_registry', '0041_auto_20230816_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='update_frequency',
            field=models.TextField(blank=True, choices=[('REAL_TIME', 'Real time'), ('HOURLY', 'Hourly'), ('DAILY', 'Daily'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Every 3 months'), ('ANNUALLY', 'Annually')], help_text='The frequency at which the source updates the publication.'),
        ),
    ]
