# Generated by Django 4.2.3 on 2023-11-02 13:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("data_registry", "0043_collection_region"),
        ("data_registry", "0044_alter_task_type"),
    ]

    operations = []
