# Generated by Django 4.2.10 on 2024-04-25 01:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_registry", "0045_merge_0043_collection_region_0044_alter_task_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="context",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="<dl><dt><code>spider</code></dt><dd>The name of the spider in Kingfisher Collect</dd><dt><code>data_version</code></dt><dd>The data version of the crawl in Kingfisher Collect</dd><dt><code>job_id</code></dt><dd>The ID of the job in Scrapyd</dd><dt><code>scrapy_log</code></dt><dd>A local URL to the log file of the crawl in Scrapyd</dd><dt><code>process_id</code></dt><dd>The ID of the base collection in Kingfisher Process</dd><dt><code>process_id_pelican</code></dt><dd>The ID of the compiled collection in Kingfisher Process</dd><dt><code>pelican_id</code></dt><dd>The ID of the dataset in Pelican</dd><dt><code>pelican_dataset_name</code></dt><dd>The name of the dataset in Pelican</dd></dl>",
            ),
        ),
    ]
