# Generated by Django 4.2.11 on 2024-04-25 22:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_registry", "0046_alter_job_context"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="collection",
            name="modified",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="issue",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="issue",
            name="modified",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="end",
            field=models.DateTimeField(blank=True, null=True, verbose_name="job ended at"),
        ),
        migrations.AlterField(
            model_name="job",
            name="modified",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="start",
            field=models.DateTimeField(blank=True, null=True, verbose_name="job started at"),
        ),
        migrations.AlterField(
            model_name="license",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="license",
            name="modified",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="end",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="modified",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="start",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
