# Generated by Django 4.2.11 on 2024-04-25 23:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_registry", "0047_alter_collection_created_alter_collection_modified_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="status",
            field=models.TextField(
                blank=True,
                choices=[
                    ("WAITING", "WAITING"),
                    ("PLANNED", "PLANNED"),
                    ("RUNNING", "RUNNING"),
                    ("COMPLETED", "COMPLETED"),
                ],
                default="PLANNED",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.TextField(
                blank=True,
                choices=[
                    ("WAITING", "WAITING"),
                    ("PLANNED", "PLANNED"),
                    ("RUNNING", "RUNNING"),
                    ("COMPLETED", "COMPLETED"),
                ],
                default="PLANNED",
            ),
        ),
    ]
