# Generated by Django 4.2.11 on 2024-04-26 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_registry", "0048_alter_job_status_alter_task_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="license_custom",
            field=models.ForeignKey(
                blank=True,
                help_text="If not set, the Overview section will display the license URL within the OCDS package.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="data_registry.license",
                verbose_name="data license",
            ),
        ),
        migrations.AlterField(
            model_name="issue",
            name="collection",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="data_registry.collection"),
        ),
        migrations.AlterField(
            model_name="job",
            name="collection",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="data_registry.collection", verbose_name="publication"
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="job",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="data_registry.job"),
        ),
    ]
