# Generated by Django 4.2.16 on 2024-11-06 04:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_registry", "0051_remove_task_context"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="additional_data",
            field=models.TextField(
                blank=True,
                help_text="Any notable highlights about the available data, such as extensions used or additional fields, as Markdown text.",
                verbose_name="data availability",
            ),
        ),
        migrations.AlterField(
            model_name="collection",
            name="additional_data_en",
            field=models.TextField(
                blank=True,
                help_text="Any notable highlights about the available data, such as extensions used or additional fields, as Markdown text.",
                null=True,
                verbose_name="data availability",
            ),
        ),
        migrations.AlterField(
            model_name="collection",
            name="additional_data_es",
            field=models.TextField(
                blank=True,
                help_text="Any notable highlights about the available data, such as extensions used or additional fields, as Markdown text.",
                null=True,
                verbose_name="data availability",
            ),
        ),
        migrations.AlterField(
            model_name="collection",
            name="additional_data_ru",
            field=models.TextField(
                blank=True,
                help_text="Any notable highlights about the available data, such as extensions used or additional fields, as Markdown text.",
                null=True,
                verbose_name="data availability",
            ),
        ),
        migrations.AlterField(
            model_name="collection",
            name="description",
            field=models.TextField(
                blank=True,
                help_text='The first paragraph of the description of the publication, as Markdown text, following the <a href="https://docs.google.com/document/d/1Pr87zDrs9YY7BEvr_e6QjOy0gexs06dU9ES2_-V7Lzw/edit#heading=h.fksp8fxgoi7v">template and guidance</a>.',
            ),
        ),
        migrations.AlterField(
            model_name="collection",
            name="description_en",
            field=models.TextField(
                blank=True,
                help_text='The first paragraph of the description of the publication, as Markdown text, following the <a href="https://docs.google.com/document/d/1Pr87zDrs9YY7BEvr_e6QjOy0gexs06dU9ES2_-V7Lzw/edit#heading=h.fksp8fxgoi7v">template and guidance</a>.',
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="collection",
            name="description_es",
            field=models.TextField(
                blank=True,
                help_text='The first paragraph of the description of the publication, as Markdown text, following the <a href="https://docs.google.com/document/d/1Pr87zDrs9YY7BEvr_e6QjOy0gexs06dU9ES2_-V7Lzw/edit#heading=h.fksp8fxgoi7v">template and guidance</a>.',
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="collection",
            name="description_long",
            field=models.TextField(
                blank=True,
                help_text='The remaining paragraphs of the description of the publication, as Markdown text, which will appear under "Show more".',
            ),
        ),
        migrations.AlterField(
            model_name="collection",
            name="description_long_en",
            field=models.TextField(
                blank=True,
                help_text='The remaining paragraphs of the description of the publication, as Markdown text, which will appear under "Show more".',
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="collection",
            name="description_long_es",
            field=models.TextField(
                blank=True,
                help_text='The remaining paragraphs of the description of the publication, as Markdown text, which will appear under "Show more".',
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="collection",
            name="description_long_ru",
            field=models.TextField(
                blank=True,
                help_text='The remaining paragraphs of the description of the publication, as Markdown text, which will appear under "Show more".',
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="collection",
            name="description_ru",
            field=models.TextField(
                blank=True,
                help_text='The first paragraph of the description of the publication, as Markdown text, following the <a href="https://docs.google.com/document/d/1Pr87zDrs9YY7BEvr_e6QjOy0gexs06dU9ES2_-V7Lzw/edit#heading=h.fksp8fxgoi7v">template and guidance</a>.',
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="collection",
            name="summary",
            field=models.TextField(
                blank=True,
                help_text="A short summary of quality issues, as Markdown text.",
                verbose_name="quality summary",
            ),
        ),
        migrations.AlterField(
            model_name="collection",
            name="summary_en",
            field=models.TextField(
                blank=True,
                help_text="A short summary of quality issues, as Markdown text.",
                null=True,
                verbose_name="quality summary",
            ),
        ),
        migrations.AlterField(
            model_name="collection",
            name="summary_es",
            field=models.TextField(
                blank=True,
                help_text="A short summary of quality issues, as Markdown text.",
                null=True,
                verbose_name="quality summary",
            ),
        ),
        migrations.AlterField(
            model_name="collection",
            name="summary_ru",
            field=models.TextField(
                blank=True,
                help_text="A short summary of quality issues, as Markdown text.",
                null=True,
                verbose_name="quality summary",
            ),
        ),
        migrations.AlterField(
            model_name="license",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="A brief description of the permissions, conditions and limitations, as Markdown text.",
            ),
        ),
        migrations.AlterField(
            model_name="license",
            name="description_en",
            field=models.TextField(
                blank=True,
                help_text="A brief description of the permissions, conditions and limitations, as Markdown text.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="license",
            name="description_es",
            field=models.TextField(
                blank=True,
                help_text="A brief description of the permissions, conditions and limitations, as Markdown text.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="license",
            name="description_ru",
            field=models.TextField(
                blank=True,
                help_text="A brief description of the permissions, conditions and limitations, as Markdown text.",
                null=True,
            ),
        ),
    ]
