# Generated by Django 4.2.16 on 2024-11-06 05:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("data_registry", "0052_alter_collection_additional_data_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Issue",
        ),
    ]
