# Generated by Django 4.2.16 on 2024-11-06 05:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("data_registry", "0053_delete_issue"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="active",
        ),
    ]
