# Generated by Django 4.2.16 on 2024-11-06 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_registry", "0054_remove_job_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="active_job",
            field=models.ForeignKey(
                blank=True,
                help_text="A job is a set of tasks to collect and process data from a publication. A job can be selected once it is completed. If a new job completes, it becomes the active job.",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="active_collection",
                to="data_registry.job",
                verbose_name="active job",
            ),
        ),
    ]
