# Generated by Django 4.2.16 on 2024-11-07 17:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_registry", "0057_collection_publication_policy_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="update_frequency",
            field=models.TextField(
                blank=True,
                choices=[
                    ("UNKNOWN", "Unknown"),
                    ("REAL_TIME", "Real time"),
                    ("HOURLY", "Hourly"),
                    ("DAILY", "Daily"),
                    ("WEEKLY", "Weekly"),
                    ("MONTHLY", "Monthly"),
                    ("QUARTERLY", "Every 3 months"),
                    ("HALF_YEARLY", "Every 6 months"),
                    ("ANNUALLY", "Annually"),
                ],
                default="UNKNOWN",
                help_text="The frequency at which the source updates the publication.",
            ),
        ),
    ]
