# Generated by Django 4.2.14 on 2024-12-18 19:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_registry", "0058_alter_collection_update_frequency"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="process_notes",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="The collection notes from Kingfisher Process.",
            ),
        ),
    ]
