# Generated by Django 4.2.18 on 2025-02-06 04:06

# https://github.com/cookiecutter/cookiecutter-django/blob/9f88202/%7B%7Bcookiecutter.project_slug%7D%7D/%7B%7Bcookiecutter.project_slug%7D%7D/contrib/sites/migrations/0003_set_site_domain_and_name.py

from django.conf import settings
from django.db import migrations


def update_site_forward(apps, schema_editor):
    Site = apps.get_model("sites", "Site")
    Site.objects.update_or_create(
        id=settings.SITE_ID,
        defaults={"domain": "data.open-contracting.org", "name": "OCP Data Registry"},
    )


def update_site_backward(apps, schema_editor):
    Site = apps.get_model("sites", "Site")
    Site.objects.update_or_create(
        id=settings.SITE_ID,
        defaults={"domain": "example.com", "name": "example.com"},
    )


class Migration(migrations.Migration):
    dependencies = [
        ("data_registry", "0060_alter_job_context"),
    ]

    operations = [
        migrations.RunPython(update_site_forward, update_site_backward),
    ]
