# Generated by Django 4.2.18 on 2025-04-03 13:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_registry", "0061_auto_20250206_0406"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="no_data_rationale",
            field=models.TextField(
                default="",
                blank=True,
                help_text="A short rationale of why an existing publication does not have data in the Data Registry. If thisfield is set, then the collection should be frozen and their retrieval frequency set to NEVER",
                verbose_name="no data rationale",
            ),
        ),
        migrations.AddField(
            model_name="collection",
            name="no_data_rationale_en",
            field=models.TextField(
                default="",
                blank=True,
                help_text="A short rationale of why an existing publication does not have data in the Data Registry. If thisfield is set, then the collection should be frozen and their retrieval frequency set to NEVER",
                verbose_name="no data rationale",
            ),
        ),
        migrations.AddField(
            model_name="collection",
            name="no_data_rationale_es",
            field=models.TextField(
                default="",
                blank=True,
                help_text="A short rationale of why an existing publication does not have data in the Data Registry. If thisfield is set, then the collection should be frozen and their retrieval frequency set to NEVER",
                verbose_name="no data rationale",
            ),
        ),
        migrations.AddField(
            model_name="collection",
            name="no_data_rationale_ru",
            field=models.TextField(
                default="",
                blank=True,
                help_text="A short rationale of why an existing publication does not have data in the Data Registry. If thisfield is set, then the collection should be frozen and their retrieval frequency set to NEVER",
                verbose_name="no data rationale",
            ),
        ),
        migrations.AlterField(
            model_name="collection",
            name="public",
            field=models.BooleanField(
                default=False,
                help_text="If the active job's tasks completed without errors or no_data_rationale is set, and all the fieldsbelow in all languages are filled in, check this box to make the publication visible to anonymous users. Otherwise, it is visible to administrators only.",
            ),
        ),
    ]
