# Generated by Django 4.2.18 on 2025-05-18 05:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_registry", "0062_collection_no_data_rationale_alter_collection_public"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="no_data_rationale",
            field=models.TextField(
                blank=True,
                help_text="The short reason why the publication has no active job. If set, freeze the publication.",
                verbose_name="no data rationale",
            ),
        ),
        migrations.AlterField(
            model_name="collection",
            name="no_data_rationale_en",
            field=models.TextField(
                blank=True,
                help_text="The short reason why the publication has no active job. If set, freeze the publication.",
                null=True,
                verbose_name="no data rationale",
            ),
        ),
        migrations.AlterField(
            model_name="collection",
            name="no_data_rationale_es",
            field=models.TextField(
                blank=True,
                help_text="The short reason why the publication has no active job. If set, freeze the publication.",
                null=True,
                verbose_name="no data rationale",
            ),
        ),
        migrations.AlterField(
            model_name="collection",
            name="no_data_rationale_ru",
            field=models.TextField(
                blank=True,
                help_text="The short reason why the publication has no active job. If set, freeze the publication.",
                null=True,
                verbose_name="no data rationale",
            ),
        ),
        migrations.AlterField(
            model_name="collection",
            name="public",
            field=models.BooleanField(
                default=False,
                help_text="If the active job's tasks completed without errors or 'No data rationale' is set, and all fields below in all languages are filled in, check this box to make the publication visible to anonymous users. Otherwise, it is visible to administrators only.",
            ),
        ),
    ]
