# Generated by Django 4.2.18 on 2025-06-26 20:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_registry", "0064_alter_job_context_alter_task_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="coverage",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="The collection compiled releases coverage from Cardinal.",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="type",
            field=models.TextField(
                blank=True,
                choices=[
                    ("collect", "Collect"),
                    ("process", "Process"),
                    ("exporter", "Exporter"),
                    ("coverage", "Coverage"),
                    ("flattener", "Flattener"),
                ],
            ),
        ),
    ]
