# Generated by Django 4.2.18 on 2025-09-02 18:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_registry", "0066_alter_job_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="date_from",
            field=models.DateField(
                blank=True,
                help_text="If not set, the job will get it from the data",
                null=True,
                verbose_name="minimum release date",
            ),
        ),
        migrations.AddField(
            model_name="collection",
            name="date_to",
            field=models.DateField(
                blank=True,
                help_text="If not set, the job will get it from the data",
                null=True,
                verbose_name="maximum release date",
            ),
        ),
        migrations.AddField(
            model_name="collection",
            name="ocid_prefix",
            field=models.TextField(
                blank=True,
                help_text="If not set, the job will get it from the data",
                verbose_name="OCID prefix",
            ),
        ),
    ]
