# Generated by Django 4.2.22 on 2025-12-19 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_registry", "0067_collection_date_from_collection_date_to_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskNote",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("level", models.TextField(choices=[("WARNING", "WARNING"), ("ERROR", "ERROR")])),
                ("note", models.TextField()),
                ("data", models.JSONField(blank=True, default=dict)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("task", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="data_registry.task")),
            ],
            options={
                "verbose_name": "task note",
                "indexes": [models.Index(fields=["task", "level"], name="data_regist_task_id_20ee8b_idx")],
            },
        ),
    ]
