# Generated by Django 4.2.22 on 2025-12-19 21:20

from django.db import migrations


def migrate_process_notes_to_tasknote(apps, schema_editor):
    Job = apps.get_model("data_registry", "Job")
    Task = apps.get_model("data_registry", "Task")
    TaskNote = apps.get_model("data_registry", "TaskNote")

    notes = []
    for job in Job.objects.exclude(process_notes={}):
        try:
            process_task = Task.objects.get(job=job, type="process")
        except Task.DoesNotExist:
            continue

        for level in ("WARNING", "ERROR"):
            for note, data in job.process_notes.get(level, []):
                notes.append(TaskNote(task=process_task, level=level, note=note, data=data))

    TaskNote.objects.bulk_create(notes, batch_size=1000)


def migrate_tasknote_to_process_notes(apps, schema_editor):
    Job = apps.get_model("data_registry", "Job")
    Task = apps.get_model("data_registry", "Task")
    TaskNote = apps.get_model("data_registry", "TaskNote")

    for job in Job.objects.all():
        try:
            process_task = Task.objects.get(job=job, type="process")
        except Task.DoesNotExist:
            continue

        process_notes = {"WARNING": [], "ERROR": []}
        for note in TaskNote.objects.filter(task=process_task):
            process_notes[note.level].append([note.note, note.data])

        if process_notes["WARNING"] or process_notes["ERROR"]:
            job.process_notes = process_notes
            job.save(update_fields=["process_notes"])


class Migration(migrations.Migration):
    dependencies = [
        ("data_registry", "0068_add_tasknote_model"),
    ]

    operations = [
        migrations.RunPython(migrate_process_notes_to_tasknote, migrate_tasknote_to_process_notes),
    ]
