# Generated by Django 4.2.22 on 2025-12-19 21:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("data_registry", "0069_migrate_process_notes_to_tasknote"),
    ]

    operations = [
        migrations.RemoveField(model_name="job", name="process_notes"),
    ]
