# Generated by Django 4.2.22 on 2026-01-09 18:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_registry", "0070_remove_job_process_notes_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasknote",
            name="level",
            field=models.TextField(
                choices=[("WARNING", "WARNING"), ("ERROR", "ERROR"), ("CRITICAL", "CRITICAL"), ("UNKNOWN", "UNKNOWN")]
            ),
        ),
    ]
