# Generated by Django 4.2.22 on 2026-01-09 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_registry", "0071_alter_tasknote_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="date_from",
            field=models.DateField(
                blank=True,
                help_text="If not set, the value calculated from the OCDS data is displayed.",
                null=True,
                verbose_name="minimum release date",
            ),
        ),
        migrations.AlterField(
            model_name="collection",
            name="date_to",
            field=models.DateField(
                blank=True,
                help_text="If not set, the value calculated from the OCDS data is displayed.",
                null=True,
                verbose_name="maximum release date",
            ),
        ),
        migrations.AlterField(
            model_name="collection",
            name="license_custom",
            field=models.ForeignKey(
                blank=True,
                help_text="If not set, the license URL within the OCDS package is displayed.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="data_registry.license",
                verbose_name="data license",
            ),
        ),
        migrations.AlterField(
            model_name="collection",
            name="ocid_prefix",
            field=models.TextField(
                blank=True,
                help_text="If not set, the value calculated from the OCDS data is displayed.",
                verbose_name="OCID prefix",
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="context",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="<dl><dt><code>spider</code></dt><dd>The name of the spider in Kingfisher Collect</dd><dt><code>data_version</code></dt><dd>The data version of the crawl in Kingfisher Collect</dd><dt><code>job_id</code></dt><dd>The ID of the job in Scrapyd</dd><dt><code>scrapy_log</code></dt><dd>A local URL to the log file of the crawl in Scrapyd</dd><dt><code>process_id</code></dt><dd>The ID of the base collection in Kingfisher Process</dd><dt><code>process_compiled_collection_id</code></dt><dd>The ID of the compiled collection in Kingfisher Process</dd></dl>",
            ),
        ),
    ]
