# Generated by Django 4.2.22 on 2026-01-13 18:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("data_registry", "0072_alter_collection_date_from_alter_collection_date_to_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="collection",
            name="title_en",
        ),
        migrations.RemoveField(
            model_name="collection",
            name="title_es",
        ),
        migrations.RemoveField(
            model_name="collection",
            name="title_ru",
        ),
    ]
