# Generated by Django 4.2.22 on 2026-01-13 19:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_registry", "0073_make_title_nontranslatable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="retrieval_frequency",
            field=models.TextField(
                blank=True,
                choices=[
                    ("WEEKLY", "Weekly"),
                    ("BIWEEKLY", "Every 2 weeks"),
                    ("MONTHLY", "Monthly"),
                    ("HALF_YEARLY", "Every 6 months"),
                    ("ANNUALLY", "Annually"),
                    ("NEVER", "This dataset is no longer updated by the publisher"),
                ],
                help_text="The frequency at which the registry updates the publication, based on the frequency at which the publication is updated.",
            ),
        ),
    ]
