# Generated by Django 5.2.12 on 2026-06-26 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_registry", "0074_add_weekly_biweekly_frequencies"),
    ]

    operations = [
        migrations.CreateModel(
            name="SettingsBundle",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.TextField(help_text='A label for the bundle, like "opentender.eu (Cloudflare)".')),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Scrapy settings bundle",
            },
        ),
        migrations.AddField(
            model_name="collection",
            name="settings_bundle",
            field=models.ForeignKey(
                blank=True,
                help_text="Additional Scrapy settings to send when scheduling crawls.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="data_registry.settingsbundle",
            ),
        ),
        migrations.CreateModel(
            name="Setting",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("key", models.TextField(help_text='The name of a Scrapy setting, like "CF_CLEARANCE".')),
                ("value", models.TextField(blank=True, help_text="The value of the Scrapy setting.")),
                (
                    "bundle",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="data_registry.settingsbundle"),
                ),
            ],
            options={
                "ordering": ["key"],
                "constraints": [models.UniqueConstraint(fields=("bundle", "key"), name="unique_bundle_key")],
            },
        ),
    ]
